DROP TABLE IF EXISTS t_customer;
CREATE TABLE t_customer(
	id BIGINT(20) PRIMARY KEY comment '主键ID',
	code VARCHAR(20) NOT NULL COMMENT '编号',
	name VARCHAR(64) NOT NULL COMMENT '名称',
	pro_id BIGINT(20) NOT NULL COMMENT '省份ID',
	pro_name VARCHAR(32) NOT NULL COMMENT '省份姓名',
	city_id BIGINT(20) NOT NULL COMMENT '城市ID',
	city_name VARCHAR(64) NOT NULL COMMENT '城市名称',
	county_id BIGINT(20) NOT NULL COMMENT '区县ID',
	county_name VARCHAR(64) NOT NULL COMMENT '区县名称',
	address VARCHAR(128) NOT NULL COMMENT '详细地址',
	telephone VARCHAR(32) NOT NULL COMMENT '座机',
	pinyin VARCHAR(128) NOT NULL COMMENT '名称全拼',
	pinyin_abbr VARCHAR(32) NOT NULL COMMENT '名称拼音首字母',
	remarks VARCHAR(128) NOT NULL COMMENT '备注',
	create_user_id BIGINT(20) NOT NULL COMMENT '创建人ID',
	create_user_name VARCHAR(32) NOT NULL COMMENT '创建人姓名',
	create_time DATETIME NOT NULL COMMENT '创建时间',
	update_user_id BIGINT(20) NOT NULL COMMENT '最后修改人ID',
	update_user_name VARCHAR(32) NOT NULL COMMENT '最后修改人姓名',
	update_time DATETIME NOT NULL COMMENT '最后修改时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户';

DROP TABLE IF EXISTS t_linkman;
CREATE TABLE t_linkman(
	id BIGINT(20) PRIMARY KEY comment '主键ID',
	customer_id BIGINT(20) NOT NULL COMMENT '客户ID',
	code VARCHAR(20) NOT NULL COMMENT '编号',
	name VARCHAR(64) NOT NULL COMMENT '姓名',
	pro_id BIGINT(20) NOT NULL COMMENT '省份ID',
	pro_name VARCHAR(32) NOT NULL COMMENT '省份姓名',
	city_id BIGINT(20) NOT NULL COMMENT '城市ID',
	city_name VARCHAR(64) NOT NULL COMMENT '城市名称',
	county_id BIGINT(20) NOT NULL COMMENT '区县ID',
	county_name VARCHAR(64) NOT NULL COMMENT '区县名称',
	address VARCHAR(128) NOT NULL COMMENT '详细地址',
	id_card_no VARCHAR(18) NOT NULL COMMENT '身份证号码',
	mobile VARCHAR(32) NOT NULL COMMENT '手机号',
	telephone VARCHAR(32) NOT NULL COMMENT '座机',
	pinyin VARCHAR(128) NOT NULL COMMENT '姓名全拼',
	pinyin_abbr VARCHAR(32) NOT NULL COMMENT '姓名拼音首字母',
	remarks VARCHAR(128) NOT NULL COMMENT '备注',
	create_user_id BIGINT(20) NOT NULL COMMENT '创建人ID',
	create_user_name VARCHAR(32) NOT NULL COMMENT '创建人姓名',
	create_time DATETIME NOT NULL COMMENT '创建时间',
	update_user_id BIGINT(20) NOT NULL COMMENT '最后修改人ID',
	update_user_name VARCHAR(32) NOT NULL COMMENT '最后修改人姓名',
	update_time DATETIME NOT NULL COMMENT '最后修改时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户联系人';

DROP TABLE IF EXISTS t_waybill;
CREATE TABLE t_waybill(
	id BIGINT(20) PRIMARY KEY comment '主键ID',
	waybill_no VARCHAR(20) NOT NULL UNIQUE COMMENT '运单号',
	sender VARCHAR(64) NOT NULL COMMENT '发货人',
	sender_code VARCHAR(20) NOT NULL COMMENT '发货人编号',
	sender_id BIGINT(20) NOT NULL COMMENT '发货人ID',
	sender_customer_id BIGINT(20) NOT NULL COMMENT '发货客户ID',
	sender_customer_name BIGINT(20) NOT NULL COMMENT '发货客户名称',
	sender_pro_id BIGINT(20) NOT NULL COMMENT '发货省份ID',
	sender_pro_name VARCHAR(32) NOT NULL COMMENT '发货省份姓名',
	sender_city_id BIGINT(20) NOT NULL COMMENT '发货城市ID',
	sender_city_name VARCHAR(64) NOT NULL COMMENT '发货城市名称',
	sender_county_id BIGINT(20) NOT NULL COMMENT '发货区县ID',
	sender_county_name VARCHAR(64) NOT NULL COMMENT '发货区县名称',
	sender_address VARCHAR(128) NOT NULL COMMENT '发货详细地址',
	sender_id_card_no VARCHAR(18) NOT NULL COMMENT '发货人身份证号码',
	sender_mobile VARCHAR(32) NOT NULL COMMENT '发货人手机号',
	receiver VARCHAR(64) NOT NULL COMMENT '收货人',
	receiver_code VARCHAR(20) NOT NULL COMMENT '发货人编号',
	receiver_id BIGINT(20) NOT NULL COMMENT '发货人ID',
	receiver_customer_id BIGINT(20) NOT NULL COMMENT '发货客户ID',
	receiver_customer_name BIGINT(20) NOT NULL COMMENT '发货客户名称',
	receiver_pro_id BIGINT(20) NOT NULL COMMENT '收货省份ID',
	receiver_pro_name VARCHAR(32) NOT NULL COMMENT '收货省份姓名',
	receiver_city_id BIGINT(20) NOT NULL COMMENT '收货城市ID',
	receiver_city_name VARCHAR(64) NOT NULL COMMENT '收货城市名称',
	receiver_county_id BIGINT(20) NOT NULL COMMENT '收货区县ID',
	receiver_county_name VARCHAR(64) NOT NULL COMMENT '收货区县名称',
	receiver_address VARCHAR(128) NOT NULL COMMENT '收货详细地址',
	receiver_id_card_no VARCHAR(18) NOT NULL COMMENT '收货人身份证号码',
	receiver_mobile VARCHAR(32) NOT NULL COMMENT '收货人手机号',
	
	pickup_mode TINYINT(4) NOT NULL COMMENT '取货方式',
	delivery_mode TINYINT(4) NOT NULL COMMENT '送货方式',
	sign_receipt TINYINT(4) NOT NULL COMMENT '签收单返回方式',
	settle_mode TINYINT(4) NOT NULL COMMENT '结算方式',
	insured_value TINYINT(4) NOT NULL COMMENT '保价金额',
	payment_collection TINYINT(4) NOT NULL COMMENT '代收货款',
	
	trans_fee decimal(12,2) NOT NULL COMMENT '运费',
	pickup_fee decimal(12,2) NOT NULL COMMENT '取货费',
	delivery_fee decimal(12,2) NOT NULL COMMENT '送货费',
	packing_fee decimal(12,2) NOT NULL COMMENT '包装费',
	insured_fee decimal(12,2) NOT NULL COMMENT '保价费',
	collection_fee decimal(12,2) NOT NULL COMMENT '代收货款手续费',
	other_fee decimal(12,2) NOT NULL COMMENT '其他费用',
	total_fee decimal(12,2) NOT NULL COMMENT '总费用',
	
	payed decimal(12,2) NOT NULL COMMENT '现付',
	to_pay decimal(12,2) NOT NULL COMMENT '到付',
	sign_return_pay decimal(12,2) NOT NULL COMMENT '回单付',
	
	month_pay decimal(12,2) NOT NULL COMMENT '月结',
	
	state TINYINT(4) NOT NULL COMMENT '状态',
	
	remarks VARCHAR(128) NOT NULL COMMENT '备注',
	create_user_id BIGINT(20) NOT NULL COMMENT '创建人ID',
	create_user_name VARCHAR(32) NOT NULL COMMENT '创建人姓名',
	create_time DATETIME NOT NULL COMMENT '创建时间',
	update_user_id BIGINT(20) NOT NULL COMMENT '最后修改人ID',
	update_user_name VARCHAR(32) NOT NULL COMMENT '最后修改人姓名',
	update_time DATETIME NOT NULL COMMENT '最后修改时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='运单';